### ISSUE TITLE
prefix path settings

### ISSUE THREAD

**Issue by 201RichK** [alexschimpf/fastapi-versionizer#15]
is there a way to set prefix path using the advanced exemple ? 
like `/preprod/api/v1.0/specs`

**Comment by alexschimpf** [comment]
Do you mean like this: https://github.com/alexschimpf/fastapi-versionizer/blob/main/examples/advanced.py#L126 ?

In your case, you would do `prefix_path='/preprod/api/v{major}.{minor}'`

**Comment by alexschimpf** [comment]
I'm going to consider this issue closed. Please re-open an issue if you're still have questions or are facing some problem.
