### ISSUE TITLE
router.add_api_route support

### ISSUE THREAD

**Issue by schlitzered** [alexschimpf/fastapi-versionizer#3]
hi there,

i am using classes to organize my routes, which seems to be incompatible with the @api_version decorator.

here is a small example how such a class looks like:

``` python
class ApiUsers:
    def __init__(
            self,
            log: logging.Logger,
            authorize: Authorize,
            crud_users: CrudUsers
    ):
        self._authorize = authorize
        self._crud_users = crud_users
        self._log = log
        self._router = APIRouter(
            prefix="/users",
            tags=["users"],
        )

        self.router.add_api_route(
            "",
            self.search,
            response_model=UserGetMulti,
            response_model_exclude_unset=True,
            methods=['GET']
        )
```

is there a way to use this module with this style of managing api routes?

**Comment by alexschimpf** [comment]
Off the top of my head, I don't know exactly how the behavior of `add_api_route` and route decorators differ. But if they are similar, I would say that applying the `api_version` decorator to your route function would probably work. Have you tried this yet?

**Comment by schlitzered** [comment]
thanks, adding the decorator to the "search" function from the example above, is doing the right thing.
