### ISSUE TITLE
Obey custom openapi_url

### ISSUE THREAD

**Issue by CallumAtCarter** [alexschimpf/fastapi-versionizer#34]
The generated versioned docs should obey the `FastAPI.openapi_url` value, rather than hard coding `/openapi.json`. This is already true for `/docs` and `/redoc`.

**Comment by alexschimpf** [comment]
Ahh, i didn't realize it had a field for that. I'll release a fix today for that.

**Comment by alexschimpf** [comment]
New version 2.1.1 is out with the fix for this
