### ISSUE TITLE
Do you have any plans to support WebSocket API?

### ISSUE THREAD

**Issue by spiritlessman** [alexschimpf/fastapi-versionizer#47]
### Subject of the issue
Support versioning WebSocket API.

I just made up the 'pull request'(https://github.com/alexschimpf/fastapi-versionizer/pull/48). Could you review this?

### Your environment
* 

### Steps to reproduce
Call Versionizer().versionize() after adding some WebSocketAPI routes.

### Expected behaviour
WebSocket API should also be versioned.

### Actual behaviour
All APIWebSocketRoute is removed after Versionizer().versionize().

**Comment by alexschimpf** [comment]
I commented on the PR. Just thinking we should probably add some test coverage for websockets.

**Comment by alexschimpf** [comment]
@spiritlessman This is now available in 3.0.4. Thanks for the work!
