### ISSUE TITLE
Pypi project page has broken link

### ISSUE THREAD

**Issue by Ryandaydev** [alexschimpf/fastapi-versionizer#58]
### Subject of the issue
The Pypi page for this project includes and broken "/examples" link.

### Your environment
Website 

### Steps to reproduce
View the Pypi project page:
https://pypi.org/project/fastapi-versionizer/#description

Click on the link in this statement:
'You can find examples in the [examples](https://pypi.org/examples) directory.'

Looks like this is re-using the readme.md from the github repo, where that is a relative link to the examples in github.

### Expected behaviour
This shouldn't be a link, or it should be a hard-coded link to the github examples.

### Actual behaviour
Clicking on link goes https://pypi.org/examples and gets a 404.

**Comment by alexschimpf** [comment]
Thanks for the find. Fix is here: https://github.com/alexschimpf/fastapi-versionizer/pull/59

**Comment by alexschimpf** [comment]
Ok it's fixed: https://pypi.org/project/fastapi-versionizer/
