### ISSUE TITLE
Feature request: Keep /docs, but add vN to the selectable server field

### ISSUE THREAD

**Issue by tzmara** [alexschimpf/fastapi-versionizer#7]
First: Thanks for continueing this nice package.

Instead of (or additional) to 
- /v1/docs
- /v2/docs
- etc.

I'd like to have `/docs` again. But with selectable v1, v2, etc in the swagger field above. The part where we can select "servers":

**Servers:**
- **latest** _(selected by default)_
- **/v2** _(same as latest)_
- **/v1** _(maybe deprecated)_

**Comment by alexschimpf** [comment]
Are you asking for a single docs page where you can see all endpoints for every version, just by selecting a "server" from the dropdown? If so, I don't think this is possible with Swagger. The "servers" are just a list of base URLs you can use for a set of endpoints. I don't think it allows you to show different endpoints based on which server is selected. I could be wrong here, but that's been my understanding. I don't see a way to map a set of endpoints to a specific server.

Seems like you'd have to build this kind of thing outside of Swagger.

**Comment by kunesj** [comment]
Workaround for this is to have links in the description of original app: 
- Re-add docs to the original app with `root_app.setup()`
- Collect all doc links from sub apps and manually add them to `root_app.description`

Here is the code I use to get doc links from all sub apps:
```python
def get_sub_apps(root_app: FastAPI, root_path: str = "") -> dict[str, FastAPI]:
    """
    Returns mounted sub-applications (not recursive)
    """
    sub_apps: dict[str, FastAPI] = {}
    for route in root_app.router.routes:
        if isinstance(route, Mount) and isinstance(route.app, FastAPI):
            sub_apps[root_path + route.path] = route.app
    return sub_apps


def get_doc_links(root_app: FastAPI, root_path: str = "") -> dict[str, tuple[FastAPI, Optional[str], Optional[str]]]:
    """
    Collects links to API docs for the main app and all sub apps
    """
    results = {}

    docs_url = (root_path + root_app.docs_url) if root_app.docs_url else None
    redoc_url = (root_path + root_app.redoc_url) if root_app.redoc_url else None
    results[root_path] = (root_app, docs_url, redoc_url)

    sub_apps = get_sub_apps(root_app, root_path)
    for path, sub_app in sub_apps.items():
        results |= get_doc_links(sub_app, path)

    return results
```

**Comment by alexschimpf** [comment]
Not a bad idea. Could also think about creating our own custom HTML page for /docs, if we really wanted to.

**Comment by alexschimpf** [comment]
I'm going to close this issue for now.
1. There is now a main docs page you can include with routes from all versions.
2. There is a versions route you can include which gives you URLs of all versioned doc pages.
3. You can always customize your app description to include versioned doc links using the `callback` param. See [here](https://github.com/alexschimpf/fastapi-versionizer/blob/main/examples/docs_customization.py) for more info.
